credentials:
  usernames:
    meihu:
      name: meihu
      password: '$2b$12$xmLpC8jo1BvDhfVdUDVOW.BWJKkpLyXz0DJ2yTPifEolWWJrrx1ia' # To be replaced with hashed password
    cheng:
      name: cheng
      password: '$2b$12$mXOwgkMw7fMDvVe5WMf8M.S16i.97eVmpQRbePhaZ0ISub8BO1yD.' # To be replaced with hashed password
    admin:
      name: admin
      password: '$2b$12$oMwkDBCi5mUuwsUrQ5JHL.siZaPqgoR3k148AbcX0K2MTi.N10CEe'
cookie:
  expiry_days: 0.02
  key: some_signature_key
  name: some_cookie_name